### ISSUE TITLE
Custom Frontend UI or Raw Streaming Data

### ISSUE THREAD

**Issue by Ali6114** [maia-sdr/maia-sdr#100]
Is it possible to build a custom UI using programming languages like Python or JavaScript to visualize streaming network data, or am I mistaken?

What if I only want to get the waterfall data in an array and use it in my own way with other applications?

**Comment by daniestevez** [comment]
Yes. This is possible. maia-httpd uses a REST API and WebSockets, so you can interact with it with a third-party application. See https://github.com/maia-sdr/maia-sdr/blob/main/maia-httpd/util/spectrum_client.py and https://github.com/daniestevez/jupyter_notebooks/blob/master/eshail2/WB-transponder-usage/record-wb-transponder.py for some simple examples.

**Comment by Ali6114** [comment]
Is there any documentation available to interact with the API using web socket?

**Comment by daniestevez** [comment]
There is no documentation, but the [documentation for maia-json](https://docs.rs/maia-json/latest/maia_json/) plus looking at how the regular web UI (maia-wasm) interacts with (maia-http) by running it with the Developer Tools network view (F12 in Firefox) is probably enough to get a good grasp.

**Comment by Ali6114** [comment]
Alright, thanks for your quick responses. I'll work on integrating the API with a third-party program.

**Comment by Ali6114** [comment]
Does Maia SDR Firmware out Raw IQ data samples?

**Comment by daniestevez** [comment]
No.

**Comment by daniestevez** [comment]
I'm closing this, since it was more of a question than an issue. Streaming of raw IQ data isn't implemented at the moment, but it may come at some point in the future.
