### ISSUE TITLE
Estimate for Parks-McClellan FIR length is different from origin paper

### ISSUE THREAD

**Issue by CMelz** [maia-sdr/maia-sdr#104]
The estimate is implemented [here](https://github.com/maia-sdr/maia-sdr/blob/c6e0b17c135da19c952b321d951e3830df060f1c/maia-httpd/src/ddc.rs#L414). From Fig.11(a) of the paper which it referred to, `ichige(0.1, 0.03, 0.1, 0.001)` shall return a value around 40, probably 39, but it returns 63. Or did I miss something?

```rust
use std::f64::consts::PI;

fn main() {
    // is 63, shall be 39
    let f11a = ichige(0.1, 0.03, 0.1, 0.001);
    println!("{f11a}");

    // is 67, shall be around 109
    let f11b = ichige(0.1, 0.05, 0.01, 0.0001);
    println!("{f11b}")
}

// copied
// Estimate for Parks-McClellan FIR length from
//
// K. Ichige, M. Iwaki and R. Ishii, "Accurate estimation of minimum filter
// length for optimum FIR digital filters," in IEEE Transactions on Circuits and
// Systems II: Analog and Digital Signal Processing, vol. 47, no. 10,
// pp. 1008-1016, Oct. 2000.
fn ichige(fp: f64, delta_f: f64, delta_p: f64, delta_s: f64) -> usize {
    let nc = (1.101 * (-(2.0 * delta_p).log10()).powf(1.1) / delta_f + 1.0).ceil();
    let v = 2.325 * (-(delta_p.log10())).powf(-0.445) * delta_f.powf(-1.39);
    let g = |x: f64| 2.0 / PI * (v * (x.recip() - (0.5 - delta_f).recip())).atan();
    let n3 = (nc * (g(fp) + g(0.5 - delta_f - fp) + 1.0) / 3.0).ceil();
    let nm = 0.52 * (delta_p / delta_s).log10() / delta_f * (-(delta_p.log10())).powf(0.17);
    let h =
        |x: f64, c: f64| 2.0 / PI * (c / delta_f * (x.recip() - (0.5 - delta_f).recip())).atan();
    let dn = (nm * (h(fp, 1.1) - (h(0.5 - delta_f - fp, 0.29) - 1.0) / 2.0)).ceil();
    (n3 + dn) as usize
}

```

**Comment by daniestevez** [comment]
Good point! I don't remember how I tested the implementation of this `ichige` function, but clearly not too well, given that it doesn't match the plot in the paper. At first glance I can't find a difference between the formulas in the `ichige`  function and the formulas in the paper, so let me work the details here.

Between (8) and (9), the formula for $\hat{N}_c$ is given as
$$\hat{N}_c(\Delta F, \delta) = \lceil \frac{1.101 \\{ -\log\_{10}(2\delta)\\}^{1.1}}{\Delta F} + 1\rceil$$

According to the following formulas, this function should be evaluated in $delta = \delta_p$.

This is (15):
$$\hat{N}_4(f_p, \Delta F, \delta_p, \delta_s) = \hat{N}_3(f_p, \Delta F, \delta_p) + D\hat{N}(f_p, \Delta F, \delta_p, \delta_s).$$

And this is (11):
$$\hat{N}_3(f_p, \Delta F, \delta) = \lceil \hat{N}_c(\Delta F, \delta) \cdot \frac{g(f_p, \Delta F, \delta) + g(0.5 - \Delta F - f_p, \Delta F, \delta) + 1}{3} \rceil$$

To me it looks like the above formula for $\hat{N}_c(\Delta F, \delta_p)$ is correctly implemented as
```rust
let nc = (1.101 * (-(2.0 * delta_p).log10()).powf(1.1) / delta_f + 1.0).ceil();
```

**Comment by daniestevez** [comment]
The next thing is $g(f_p, \Delta F, \delta)$. I've already put the formula in the previous comment. The Rust code is a lambda expression that depends on `x`, which plays the role of $f_p$. This looks correct to me too:
```rust
let g = |x: f64| 2.0 / PI * (v * (x.recip() - (0.5 - delta_f).recip())).atan();
```

**Comment by daniestevez** [comment]
Then we put all of this together using (11), which I write again here for convenience:
$$\hat{N}_3(f_p, \Delta F, \delta) = \lceil \hat{N}_c(\Delta F, \delta) \cdot \frac{g(f_p, \Delta F, \delta) + g(0.5 - \Delta F - f_p, \Delta F, \delta) + 1}{3} \rceil$$
In Rust this is
```rust
let n3 = (nc * (g(fp) + g(0.5 - delta_f - fp) + 1.0) / 3.0).ceil();
```
This looks correct to me too.

**Comment by daniestevez** [comment]
Next we have (14):
$$\tilde{N}_m(\Delta F, \delta_p, \delta_s) = 0.52 \cdot \frac{\log\_{10}(\delta_p/\delta_s)}{\Delta F}\cdot(-\log\_{10}\delta_p)^{0.17}.$$
In Rust this is
```rust
let nm = 0.52 * (delta_p / delta_s).log10() / delta_f * (-(delta_p.log10())).powf(0.17);
```
Again this looks right to me.

**Comment by daniestevez** [comment]
After (15), there is the formula for $h(f_p, \Delta F, c)$. This is
$$h(f_p, \Delta F, c) = \frac{2}{\pi}\cdot \arctan \left \\{ \frac{c}{\Delta F} \cdot \left(\frac{1}{f_p} - \frac{1}{0.5 - \Delta F}\right) \right \\}.$$
In Rust this is declared as a lambda expression that depends on `x` (playing the role of $f_p$) and `c` (which is just $c$):
```rust
let h =
    |x: f64, c: f64| 2.0 / PI * (c / delta_f * (x.recip() - (0.5 - delta_f).recip())).atan();
```
This looks correct.

**Comment by daniestevez** [comment]
Finally, the formula for $D\hat{N}$ is (15):
$$D\hat{N}(f_p, \Delta F, \delta_p, \delta_s) = \lceil \hat{N}_m(\Delta F, \delta_p, \delta_s) \cdot \left \\{ h(f_p, \Delta F, 1.1) - \frac{h(0.5 - \Delta F - f_p, \Delta F, 0.29) - 1}{2} \right \\}\rceil$$
In Rust this is
```rust
let dn = (nm * (h(fp, 1.1) - (h(0.5 - delta_f - fp, 0.29) - 1.0) / 2.0)).ceil();
```

According to (15), the final result is `n3 + dn`.

So comparing the Rust code and the formulas in the paper I can't see any mistakes. I could calculate the intermediate results for the parameters from Fig. 11 (a), but since there are not intermediate values in the paper to compare against, I don't think this is helpful.

**Comment by daniestevez** [comment]
There is [this Python implementation](https://github.com/thorstenkranz/eegpy/blob/master/eegpy/filter/remezord.py#L73), which might be useful for comparison. With this I get the following (note that the second parameter is $f_c = f_p + \Delta F$ rather than $\Delta F$.
```
In [2]: remezord.remlplen_ichige(0.1, 0.1+0.03, 0.1, 0.001)
Out[2]: 63

In [3]: remezord.remlplen_ichige(0.1, 0.1+0.05, 0.01, 0.0001)
Out[3]: 67
```
This is the same that my Rust code gives, but doesn't match the Fig. 11. I've noticed that the `ichige()` function I have in Rust usually underestimates the number of taps required by the filter (as in the 2nd case, where the function says 67, but Fig. 11 says around 109). Maybe there is a typo in the formulas in the paper?

**Comment by daniestevez** [comment]
On a side note, the Python implementation (and I guess that the Rust code too) seems to match well Fig 9 (by setting $\delta_p = \delta_s = \delta$), so maybe the issue is about the correction term for the case $\delta_p \neq \delta_s$.

**Comment by daniestevez** [comment]
I've also checked that the Rust code seems to match Figure 6: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=45efa80db3b4d79b0128e2d72f7e71f6

**Comment by daniestevez** [comment]
There's something odd in the paper comparing Fig 6 and Fig 11 b). These have the same parameters except for $\delta_s$, which is `1e-5` in Fig 6 and `1e-4` in Fig 11 b), so the filter from Fig 6 should have more taps. Yet Fig 6 gives around 80 taps for $f_p = 0.1$ and Fig 11 b) gives around 110 taps.

**Comment by daniestevez** [comment]
I'm now checking minimal filter length using `pm_remez`. With the parameters of Fig 11 a), for $\delta_p = 0.1$, the minimum number of taps is 65:
```
In [7]: pm_remez.remez(64, [0, 0.1, 0.1+0.03, 0.5], [1, 0], weight=[1, 100]).weighted_error
Out[7]: 0.10032975454104867

In [8]: pm_remez.remez(65, [0, 0.1, 0.1+0.03, 0.5], [1, 0], weight=[1, 100]).weighted_error
Out[8]: 0.09821046718844288
```
This matches roughly the Rust code (it says 63), but doesn't match Fig 11 a).

For Fig 11 b) with $\delta_p = 0.1$, the minimum number of taps is 68:
```
In [15]: pm_remez.remez(67, [0, 0.1, 0.1+0.05, 0.5], [1, 0], weight=[1, 100]).weighted_error
Out[15]: 0.010501588836660046

In [16]: pm_remez.remez(68, [0, 0.1, 0.1+0.05, 0.5], [1, 0], weight=[1, 100]).weighted_error
Out[16]: 0.00981485648581205
```
The Rust code says 67 and Fig 11 b) says around 110.

So it looks to me that Fig 11 is completely wrong. Perhaps the parameters given in the figure description are incorrect.

**Comment by CMelz** [comment]
I coded the algorithm from the paper by myself both in Rust and Mathematica, and I got the same value of 63 and 67. I agree that fig.11 may be wrong.
![Mathematica codes just like the paper](https://github.com/user-attachments/assets/e8daeca9-b1a1-4fff-a3ab-7b69044b7770)
