### ISSUE TITLE
Unable to Establish WebSocket Connection with the Server

### ISSUE THREAD

**Issue by Ali6114** [maia-sdr/maia-sdr#106]
I am trying to retrieve FFT data via WebSocket using the example file spectrum_client.py. However, I am unable to establish a connection with the server. When attempting to connect to the address ws://192.168.1.10:8000, I receive an error indicating that the server refused the connection.

**Steps to Reproduce:**
Run spectrum_client.py as per the provided instructions.
Attempt to connect to the server using ws://192.168.1.10:8000.
Observe the error message indicating that the connection was refused.
Expected Behavior: The client should successfully connect to the server and receive FFT data.

**Environment:**
MaiaSDR firmware build for AntSDR E200.

**Request:** Could you please help me resolve this issue and suggest potential reasons for the connection refusal?

Thank you!

**Comment by daniestevez** [comment]
The correct URL is `ws://192.168.2.1:8000/waterfall`. See #99.

**Comment by Ali6114** [comment]
It's working now—thanks for providing the correct URL!

I was wondering if there’s a way to control settings such as frequency and sample rate through the WebSocket connection. Is this functionality supported, or would there be a method to implement it?

Thanks again!

**Comment by daniestevez** [comment]
There is a REST API to control the frequency, sample rate, etc. The best way to learn how the API works is to use the web developer tools (e.g., F12 -> Network in Firefox) on the Maia SDR web UI and see which REST API calls are done by the web UI when the buttons are pressed.

**Comment by daniestevez** [comment]
This script can also be useful as an example: https://github.com/daniestevez/jupyter_notebooks/blob/master/eshail2/WB-transponder-usage/record-wb-transponder.py

**Comment by Ali6114** [comment]
Thanks for your pointing towards the Rest API. I have one more question about the data streamed via WebSocket. It seems to be FFT or PSD values.

Could you confirm:

1. Is the data normalized or scaled?


2. If so, what scaling factor should be used to convert it to dBm?



Example data: [28.2988, 28.2006, 28.0542, ...]

Additionally, what changes will I need to make to convert the y-axis scale to dBm in the spectrum_client.py file?

I need to plot this data in dBm to analyze the power levels.

Thank you!

**Comment by daniestevez** [comment]
The spectrometer data that comes on the WebSocket is in linear units of power with respect to an arbitrary scale. To convert to dBm you need to compute `10*log10()` to convert to dB units, and to calibrate to an absolute power scale in dBm by using a calibration signal of known power.

**Comment by daniestevez** [comment]
@Ali6114 can this issue be closed?

**Comment by Ali6114** [comment]
Sure. Thanks for your support.
