### ISSUE TITLE
Typo: not conforming to SigMF specification

### ISSUE THREAD

**Issue by lukashenneke** [maia-sdr/maia-sdr#71]
Hello there,

I guess it should be ```core:datetime``` instead of ```core.datetime```.
https://github.com/maia-sdr/maia-sdr/blob/79eac6f1538b93fbe52e1f008c40714cccf18241/maia-httpd/src/sigmf.rs#L241

Thanks for your work on this great project!

**Comment by lukashenneke** [comment]
I noticed the same bug in the test (line 271)

**Comment by daniestevez** [comment]
Thanks for noticing! It seems I copypasted the typo into the test. I'll get this fixed right away.
