### ISSUE TITLE
HDL to allow for sampling time alignment between multiple plutos

### ISSUE THREAD

**Issue by Argonghost** [maia-sdr/maia-sdr#95]
Hi

i wanted to ask if there was any plan to introduce a HDL code to the Zynq to allow for sampling time alignment between mutiple pluto SDR's, as that would certainly be helpful for phase synchronization experiments between multiple pluto sdr's.  From my limited understanding there is an AXI pin in the Zynq which allows for sending out a signal that could be used for master slave configuration with another zynq in  a second pluto to trigger it in order to sample simulataneously.  This is something i've been stuck with for a long time and i've been dying to find a solution for this for the ADALM pluto.

Sincerely,
AG

**Comment by daniestevez** [comment]
Hello,

This is not in the roadmap, although it is an interesting feature. To do phase coherent reception between multiple AD936x properly, besides doing the baseband SYNC, it is also necessary to feed the same external LO to all the AD936x. I think the LO out and LO in ports are not routed in the Pluto. This is perhaps not a complete showstopper, but it is potentially problematic depending on the intended application. The Pluto is not really a good device for more than 2 coherent channels (with the two channels in the AD936x it should work just fine).

Something else that is needed to synchronize several Plutos is to timestamp the samples with an external 1PPS or trigger. This is also useful for other applications with a single Pluto. Realistically, this feature might be added to Maia SDR at some point, but for the rest, there are no plans at the moment.

**Comment by Argonghost** [comment]
> Hello,
> 
> 
> 
> This is not in the roadmap, although it is an interesting feature. To do phase coherent reception between multiple AD936x properly, besides doing the baseband SYNC, it is also necessary to feed the same external LO to all the AD936x. I think the LO out and LO in ports are not routed in the Pluto. This is perhaps not a complete showstopper, but it is potentially problematic depending on the intended application. The Pluto is not really a good device for more than 2 coherent channels (with the two channels in the AD936x it should work just fine).
> 
> 
> 
> Something else that is needed to synchronize several Plutos is to timestamp the samples with an external 1PPS or trigger. This is also useful for other applications with a single Pluto. Realistically, this feature might be added to Maia SDR at some point, but for the rest, there are no plans at the moment.

Hi Daniel

Thank you for your excellent explanation.  Although no need for RF alignment due to there not being LO pins, how would one go about SYNC logic alignment to at least align buffer sampling time?

What do you mean bu external 1 pps trigger? 

Do you mean external ref clk? Because feeding in an external clock aligns frequency but not phase (im very sorry if my understanding is incorrect & limited) 

If thats not what you meant by feeding 1 pps to align timestamp, then what does the process roughly require? I.e.  external circuitry & HDL mode?

Sincerely, 
Abdalla

**Comment by daniestevez** [comment]
> how would one go about SYNC logic alignment to at least align buffer sampling time?

See the AD936x datasheet and reference manual for how the baseband synchronization works.

> What do you mean by external 1 pps trigger?

An edge from a 1 PPS or any other trigger signal that is supplied simultaneously to several FPGAs. This is required to synchronize the sample streams across multiple FPGAs.

> Do you mean external ref clk?

No. I didn't mention external reference clock, but for sure this is also needed for synchronized operation.

**Comment by Argonghost** [comment]
> > how would one go about SYNC logic alignment to at least align buffer sampling time?
> 
> 
> 
> See the AD936x datasheet and reference manual for how the baseband synchronization works.
> 
> 
> 
> > What do you mean by external 1 pps trigger?
> 
> 
> 
> An edge from a 1 PPS or any other trigger signal that is supplied simultaneously to several FPGAs. This is required to synchronize the sample streams across multiple FPGAs.
> 
> 
> 
> > Do you mean external ref clk?
> 
> 
> 
> No. I didn't mention external reference clock, but for sure this is also needed for synchronized operation.

Hi, 

Sorry for making this a big issue but as ive explained im trying to gather as much info as possible about phase synchronization.  

So regarding the documentation on AD936x BB synchronization, this is intended for FMCOMMS5 board because it has the LO u.fl ports & logic pins for that.  Its not for Pluto.  How would one go on doing an FPGA sync for pluto? 

Sincerely, 
AG
