### ISSUE TITLE
About the usage of spectrum client

### ISSUE THREAD

**Issue by ahmetakman** [maia-sdr/maia-sdr#99]
This repo is definitely a great piece of engineering. I would like to ask about the usage of spectrum client python code provided in httpd part. Even though I can reach the server in the browser perfectly on http://192.168.2.1:8000/ I can not get the python code connect by calling ` python spectrum_client.py ws://192.168.2.1:8000`  and I get the error as follows
`    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200`

Maybe I misunderstood what I should provide as the websocket adress . I somehow  could not get the WebSocket connection.

Best,

**Comment by daniestevez** [comment]
You need to use the full URL for the websocket endpoint. It is ws://192.168.2.1:8000/waterfall

The point is that in the future there could be different endpoints for different things.

**Comment by ahmetakman** [comment]
Thanks I a lot, I just noticed it by looking at the inspect part. Thanks also for the fast response.

Cheers.
